# PostgreSQL. Versions 8.2 and up are supported.

development:
  adapter: postgresql
  encoding: unicode
  database: ryan-menu_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: ryan-menu_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: ryan-menu_production
  pool: 5
